#!/bin/bash
# echo "a.b.c.txt" | rev | cut -d"." -f2-  | rev

printf "Your are logged into database engine\nYou can create database, Create table, Insert, Update or delete\n"
while [ = ]
do
function create {
	case $1 in
	'database')
	if [ -d $2 ] && [ $# -eq 2 ]
	then
	echo "$2  already exsit"
	 
	else
	mkdir $2
	printf "\n$2 has been created at home directory\n"
 
	fi
	;;
	'table')   #table$1 x$2 in$3 DB$4
	if [  $3 = 'in' ]  && [ $# -eq 4  ] &&  [ -d $4  ] &&  [  ! -f $2   ]
	then
	if [[  -f $2 ]]
	then
	echo "\n $4 error 401 table already exist"
	else 
	cd $4
	touch $2
	printf "\n$2 table has been created in $4\n"
	 fi
	
	else
	echo "\n $4 error 401 table already exist or Database not found"
	 
	fi	

	
	;;
	*)
	printf "\n invalid name $2 {table or database} \n"
	 
	;;
	esac 

}
#echo "$string2"
#echo "$string3"
 

pwd
ls

read -p 'ourDB> ' cmd
  
string1="$(cut -d' '  -f1 <<< $cmd)"
string2="$(cut -d' '  -f2 <<< $cmd)"
string3="$(cut -d' '  -f3 <<< $cmd)"
string4="$(cut -d' '  -f4 <<< $cmd)"
string5="$(cut -d' '  -f5 <<< $cmd)"

	 
 if [ $string1 = 'create' ];
then
echo "$string1";
cd ;
pwd ;
create  $string2 $string3 $string4 $string5
else
echo 'wrong input';
 
fi
    done
 


